package hubspotmodels

import (
	communicationmodels "github.com/karman-digital/hubspot/hubspot/api/models/communicationpreferences"
	sharedmodels "github.com/karman-digital/hubspot/hubspot/api/models/shared"
)

type CommunicationPreferencesResponse = communicationmodels.CommunicationPreferencesResponse

type CommunicationPreferenceStatusResponse = communicationmodels.CommunicationPreferenceStatusResponse

type SubscriptionDefinition = communicationmodels.SubscriptionDefinition

type CommunicationPreferencesPostBody = communicationmodels.CommunicationPreferencesPostBody

type CommunicationLegalBasis = communicationmodels.CommunicationLegalBasis

type SubscriptionStatus = communicationmodels.SubscriptionStatus

type BatchCommunicationPreferencesPostBody = communicationmodels.BatchCommunicationPreferencesPostBody

type CommunicationPreferencesBatchInput = communicationmodels.CommunicationPreferencesBatchInput

type BatchCommunicationPreferencesResponse = communicationmodels.BatchCommunicationPreferencesResponse

type V4CommunicationPreferenceResult = communicationmodels.V4CommunicationPreferenceResult

type BatchResponseBase = sharedmodels.BatchResponseBase
